color0 #e3e8e8
color1 #fd4663
color2 #22c3bd
color3 #296da3
color4 #2d3086
color5 #17827e
color6 #1b527e
color7 #181b1b
color8 #558e8c
color9 #fd4663
color10 #22c3bd
color11 #296da3
color12 #2d3086
color13 #17827e
color14 #1b527e
color15 #181b1b

cursor                #181b1b
cursor_text_color     #e3e8e8
background            #e3e8e8
foreground            #181b1b
selection_foreground  #4f5757
selection_background  #c1cccc
active_border_color   #22c3bd
inactive_border_color #c1cccc
url_color             #22c3bd

active_tab_foreground   #202626
active_tab_background   #22c3bd
inactive_tab_foreground #4f5757
inactive_tab_background #c1cccc
cursor_trail_color      #4f5757
