# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252730)
$foreground = rgb(D4D6D9)
$color0 = rgb(4A4D56)
$color1 = rgb(011D3E)
$color2 = rgb(011D3E)
$color3 = rgb(072241)
$color4 = rgb(2A2F35)
$color5 = rgb(3F4C5C)
$color6 = rgb(64686D)
$color7 = rgb(BABDC0)
$color8 = rgb(828486)
$color9 = rgb(012753)
$color10 = rgb(012753)
$color11 = rgb(092D57)
$color12 = rgb(383E47)
$color13 = rgb(53657A)
$color14 = rgb(858B92)
$color15 = rgb(BABDC0)
