# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf

dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_status = master
  new_on_top = 1
  mfact = 0.5
}

general {
  resize_on_border = true
     
  layout = dwindle
}

input {
  # Added 'ar' to the list. You now have French, US English, and Arabic.
  kb_layout = fr,ara
  kb_variant =
  kb_model =
  
  # This adds the toggle. Pressing ALT + SHIFT will cycle through FR -> US -> AR
  kb_options = grp:alt_shift_toggle
  
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  
  sensitivity = 0 
  numlock_by_default = true
  left_handed = false
  follow_mouse = true
  float_switch_override_focus = false

  touchpad {
    disable_while_typing = true
    natural_scroll = true 
    clickfinger_behavior = false
    middle_button_emulation = true
    tap-to-click = true
    drag_lock = false
  }
  
  touchdevice {
    enabled = true
  }
    
  tablet {
    transform = 0
    left_handed = 0
  }
}
# Swipe between workspaces
gesture = 3, horizontal, workspace


misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  vrr = 2
  mouse_move_enables_dpms = true
  enable_swallow = off
  swallow_regex = ^(kitty)$
  focus_on_activate = false
  initial_workspace_tracking = 0
  middle_click_paste = false
}

#opengl {
#  nvidia_anti_flicker = true
#}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

#Could help when scaling and not pixelating
xwayland {
  enabled = true
  force_zero_scaling = true
}

# render {
#   explicit_sync = 2
#   explicit_sync_kms = 2
#   direct_scanout = 0
# }

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = 2 # change to 1 if want to disable
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps = true 
}
