# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty (light colors only) */

foreground         #79E0F6
background         #161A1C
cursor             #049EBF

active_tab_foreground     #05D2FF
active_tab_background     #017089
inactive_tab_foreground   #559DAD
inactive_tab_background   #05D2FF

active_border_color   #017089
inactive_border_color #05D2FF
bell_border_color     #05D2FF

color0      #79E0F6
color1      #017089
color2      #05D2FF
color3      #559DAD
color4      #049EBF
color5      #017089
color6      #015467
color7      #05D2FF
color8      #79E0F6
color9      #017089
color10     #05D2FF
color11     #559DAD
color12     #049EBF
color13     #017089
color14     #015467
color15     #05D2FF