# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty (light colors only) */

foreground         #BABDC0
background         #252730
cursor             #64686D

active_tab_foreground     #858B92
active_tab_background     #53657A
inactive_tab_foreground   #828486
inactive_tab_background   #858B92

active_border_color   #53657A
inactive_border_color #858B92
bell_border_color     #858B92

color0      #BABDC0
color1      #53657A
color2      #858B92
color3      #828486
color4      #64686D
color5      #383E47
color6      #3F4C5C
color7      #858B92
color8      #BABDC0
color9      #53657A
color10     #858B92
color11     #828486
color12     #64686D
color13     #383E47
color14     #3F4C5C
color15     #858B92